name: Run Cnc tests
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Build tests container
        working-directory: ${{github.workspace}}
        run: |
          docker build -t test_cnc_img -f docker/test.dockerfile .

      - name: Run tests container
        working-directory: ${{github.workspace}}
        run: |
          docker run test_cnc_img